# Generated by Django 6.0.1 on 2026-01-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
