# Generated by Django 6.0.1 on 2026-01-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lecture_youtube_url_alter_lecture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='original_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
